/**
 * Service IDs match translation keys: services.main.{id}, services.sub.{id}
 * Each main service has 3–5 sub-services.
 */
export const SERVICE_IDS = {
  plumbing: "plumbing",
  electricity: "electricity",
  painting: "painting",
  carpentry: "carpentry",
  ac: "ac",
  flooring: "flooring",
  appliances: "appliances",
  cleaning: "cleaning",
  gypsum: "gypsum",
  telecom: "telecom",
  windows: "windows",
} as const;

export type MainServiceId = keyof typeof SERVICE_IDS;

export const MAIN_SERVICES: MainServiceId[] = [
  "plumbing",
  "electricity",
  "painting",
  "carpentry",
  "ac",
  "flooring",
  "appliances",
  "cleaning",
  "gypsum",
  "telecom",
  "windows",
];

export const SUB_SERVICES: Record<MainServiceId, string[]> = {
  plumbing: ["plumbing_leak", "plumbing_blockage", "plumbing_install", "plumbing_water_heater", "plumbing_other"],
  electricity: ["electricity_switch", "electricity_wiring", "electricity_light", "electricity_fan", "electricity_other"],
  painting: ["painting_walls", "painting_ceiling", "painting_exterior", "painting_decorative", "painting_other"],
  carpentry: ["carpentry_doors", "carpentry_furniture", "carpentry_kitchen", "carpentry_repair", "carpentry_other"],
  ac: ["ac_install", "ac_maintenance", "ac_gas", "ac_clean", "ac_other"],
  flooring: ["flooring_tiles", "flooring_parquet", "flooring_marble", "flooring_repair", "flooring_other"],
  appliances: ["appliances_washing", "appliances_fridge", "appliances_oven", "appliances_small", "appliances_other"],
  cleaning: ["cleaning_home", "cleaning_office", "cleaning_after_renovation", "cleaning_deep", "cleaning_other"],
  gypsum: ["gypsum_ceiling", "gypsum_walls", "gypsum_partition", "gypsum_repair", "gypsum_other"],
  telecom: ["telecom_landline", "telecom_router", "telecom_cctv", "telecom_intercom", "telecom_other"],
  windows: ["windows_install", "windows_aluminum", "windows_shutter", "windows_repair", "windows_other"],
};

/** Estimated cost range in EGP (min, max) per sub-service - for display only */
export const SUB_SERVICE_ESTIMATES: Record<string, [number, number]> = {
  plumbing_leak: [150, 400],
  plumbing_blockage: [200, 600],
  plumbing_install: [300, 800],
  plumbing_water_heater: [250, 700],
  plumbing_other: [150, 500],
  electricity_switch: [100, 300],
  electricity_wiring: [200, 600],
  electricity_light: [80, 250],
  electricity_fan: [150, 400],
  electricity_other: [100, 400],
  painting_walls: [800, 2500],
  painting_ceiling: [500, 1500],
  painting_exterior: [1000, 4000],
  painting_decorative: [600, 2000],
  painting_other: [400, 1500],
  carpentry_doors: [400, 1200],
  carpentry_furniture: [300, 1000],
  carpentry_kitchen: [500, 2000],
  carpentry_repair: [150, 500],
  carpentry_other: [200, 800],
  ac_install: [1500, 4000],
  ac_maintenance: [200, 500],
  ac_gas: [400, 900],
  ac_clean: [150, 350],
  ac_other: [200, 600],
  flooring_tiles: [800, 3000],
  flooring_parquet: [1000, 3500],
  flooring_marble: [1200, 5000],
  flooring_repair: [200, 800],
  flooring_other: [400, 1500],
  appliances_washing: [200, 600],
  appliances_fridge: [250, 700],
  appliances_oven: [200, 500],
  appliances_small: [100, 300],
  appliances_other: [150, 450],
  cleaning_home: [300, 800],
  cleaning_office: [400, 1200],
  cleaning_after_renovation: [500, 1500],
  cleaning_deep: [400, 1000],
  cleaning_other: [250, 700],
  gypsum_ceiling: [600, 2000],
  gypsum_walls: [500, 1800],
  gypsum_partition: [800, 2500],
  gypsum_repair: [200, 600],
  gypsum_other: [300, 1000],
  telecom_landline: [100, 300],
  telecom_router: [150, 400],
  telecom_cctv: [400, 1200],
  telecom_intercom: [300, 800],
  telecom_other: [150, 500],
  windows_install: [800, 3000],
  windows_aluminum: [600, 2500],
  windows_shutter: [400, 1500],
  windows_repair: [200, 600],
  windows_other: [300, 1000],
};
